name: "Full trigger workflow"
description: "Workflow that uses all the available triggers"

on:
  schedule: # activation every 5 minutes
    - cron: "0 0 * * *"
    - cron: "0 * * * 1,3"
  workflow_dispatch: 
  branch_protection_rule:
    types: [deleted, created]
  create: 
  gollum: 
  issues:
    types: [opened, closed, assigned]
  
    

jobs:
  print-message:
    runs-on: ubuntu-latest
  # if: ${{ github.event.issue.assignee == github.actor}} 
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v6

      - name: "Message"
        run: |
          echo "My github token is $GITHUB_TOKEN"
          echo "github.repository ${{github.repository}}"
          echo "github.action ${{github.action}}"
          echo "github.workflow ${{github.workflow}}"
          echo "github.env ${{github.env}}"
          echo "github.action_path ${{github.action_path}}"
          echo "github.action_status ${{github.action_status}}"
          echo "github.action_ref ${{github.action_ref}}"
          echo "github.action_repository ${{github.action_repository}}"
          echo "github.actor ${{github.actor}}"
          echo "vars.daniele_variable=${{ vars.DANIELE_VARIABLE }}"
          echo "secrets.daniele_secret=${{ secrets.DANIELE_SECRET }}"
    
