name: Esercizio 2 - Variabili
on: [push]
jobs: 
  job-variabili:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Stampa a schermo una certa variabile
        env:
          UTENTE: Daniele
        run: echo Ciao $UTENTE, come ti senti oggi? 
