name: Esercizio 1 - Hello World
on: [push]

jobs:
  welcome-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4
      
      - name: Messaggi di testo
        run: |
          echo Oggi è stata una bella giornata
          echo mia sorella ha compiu gli anni
          echo io li compirò il mese prossimo 
         
